cacheFolder: .yarn/cache

compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 94b425938b622e4f8ebf4dce63b3540854d9351071222ef637ab73c2dab3d47288374c9e951462f5578010e8ecd5fa7b9d6da5b79336b214e998bbceaab7e633
    path: .yarn/plugins/@yarnpkg/plugin-cyclonedx.cjs
    spec: "https://github.com/CycloneDX/cyclonedx-node-yarn/releases/latest/download/yarn-plugin-cyclonedx.cjs"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
